### PR TITLE
Task:4369 

### PR DESCRIPTION
**Pull request by surajkhariappfoster**
Added modals for edit and add user button

**For Add User**
image
**For Edit User**
image

### CODE REVIEW

**Comment by sharmarishabh1** [comment]
This whole file would come up in this branch?

why did we add it on the main branch?

image

**Comment by surajkhariappfoster** [comment]
> This whole file would come up in this branch?
> 
> why did we add it on the main branch?
> 
> image
@sharmarishabh1 
I didn't understand what you are trying to say.
May I have a brief meeting with you if you are available ?

**Comment by sharmarishabh1** [comment]
> > This whole file would come up in this branch?
> > why did we add it on the main branch?
> > image
> > @sharmarishabh1
> > I didn't understand what you are trying to say.
> > May I have a brief meeting with you if you are available ?

We basically want just the whole folder to be added - that is the main ask

**Comment by surajkhariappfoster** [comment]
> > > This whole file would come up in this branch?
> > > why did we add it on the main branch?
> > > image
> > > @sharmarishabh1
> > > I didn't understand what you are trying to say.
> > > May I have a brief meeting with you if you are available ?
> 
> We basically want just the whole folder to be added - that is the main ask

@sharmarishabh1 
but the whole folder is already there

**Comment by sharmarishabh1** [comment]
Review pointers @surajkhariappfoster 
 - add pagination
 - move add button to the right side
 - To hide the id and avoid showing it
 - add a dropdown on the gender
 - add a dropdown for status
 - avoid editing email and also email should be unique in the data table
 - add a way to add new projects and edit projects
 -  need an option for soft delete
 - add validators
 - fix database

**Pull request closed without merging**
